### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by hick999** [Jxpro/damai-tickets#3]

**Comment by hick999** [comment]
ticket2，只是使用selenium来获取登录cookie，接下来的抢票操作都是在接口层面进行，所以不会受到大麦网只能app抢票的限制是吗？

**Comment by Jxpro** [comment]
理论上是这样的，另外注意修改一下User-Agent为移动端的UA

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
