### ISSUE TITLE
登录滑块验证

### ISSUE THREAD

**Issue by akabule** [Jxpro/damai-tickets#4]
window.navigator.webdriver显示是false，但是滑块不管手动还是selenium滑动都失败，请问如何解决？

**Comment by imyuanli** [comment]
> window.navigator.webdriver显示是false，但是滑块不管手动还是selenium滑动都失败，请问如何解决？

pc 端好像目前没法搞了，看了好几个了

**Comment by Jxpro** [comment]
这个问题是webdriver特征导致的，可以通过搜索引擎或gpt等AI工具找一下解决方案
