### ISSUE TITLE
问

### ISSUE THREAD

**Issue by ghost** [Jxpro/damai-tickets#6]
不是说现在只支持app移动端吗，这个网页端的能用不

**Comment by Cocowwy** [comment]
+1 疑问

**Comment by Zoisaang** [comment]
网页端的不能用，我试过别的仓库代码了，直接显示不支持这个渠道购买票

**Comment by Jxpro** [comment]
代码仅供参考。另外app抢票需要修改请求头的user-agent为移动端。具体使用代理抓一下安卓数据包就可以拿到UA的值。
